services:
  - type: web
    name: littlane-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://atharvarathodft_db_user:z5xrhF8eJGEFNfzf@littlane.edwqy8q.mongodb.net/littlane?retryWrites=true&w=majority&appName=LITTLANE
      - key: RAZORPAY_KEY_ID
        value: rzp_live_TFRZBe5CTmpFvp
      - key: RAZORPAY_KEY_SECRET
        value: qPR3WXy0Ey42HSPqZsuZqcU5
      - key: SMTP_USER
        value: arnexora@gmail.com
      - key: SMTP_PASS
        value: nhqxcpbnfvidvjad
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: ADMIN_KEY
        value: littlane2024
      - key: BASE_URL
        sync: false
